#!/usr/bin/env node
/**
 * Apply VistaRemote environment profile to all sub-repos.
 * Usage: VISTA_ENV=local node tooling/scripts/apply-env.mjs
 *        node tooling/scripts/apply-env.mjs dev
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { envFilePath, findMetaRoot } from './lib/paths.mjs';

const metaRoot = findMetaRoot();
if (!metaRoot) {
  console.error('❌ Cannot find Meta-Repo root (config/environments).');
  process.exit(1);
}

let envName = process.argv[2] ?? process.env.VISTA_ENV;
if (!envName) {
  try {
    envName = readFileSync(join(metaRoot, '.vista-env'), 'utf8').trim();
  } catch {
    envName = 'local';
  }
}

const src = envFilePath(metaRoot, envName);
let raw;
try {
  raw = readFileSync(src, 'utf8');
} catch {
  console.error(`❌ Unknown environment: ${envName} (missing ${src})`);
  process.exit(1);
}

const vars = parseEnv(raw);
writeFileSync(join(metaRoot, '.vista-env'), `${envName}\n`, 'utf8');

const publicKeys = [
  'VISTA_ENV',
  'PUBLIC_API_BASE',
  'PUBLIC_WS_URL',
  'PUBLIC_SIGNALING_URL',
];

const mobileKeys = ['VISTA_ENV', 'EXPO_PUBLIC_API_BASE'];

const serverKeys = [
  'VISTA_ENV',
  'PORT',
  'REDIS_URL',
  'TURN_URL',
  'TURN_USERNAME',
  'TURN_CREDENTIAL',
  'MEDIASOUP_CONTROLLER_URL',
  'MEDIASOUP_SIGNALING_URL',
  'TURN_LOAD_THRESHOLD',
];

const aiKeys = [
  'VISTA_ENV',
  'REDIS_URL',
  'AI_BASE_URL',
  'AI_MODEL',
  'VECTOR_DB_URL',
  'PYTHON_ML_URL',
  'SERVER_INTERNAL_URL',
  'SERVER_INTERNAL_HMAC_SECRET',
];

const targets = [
  { path: 'server/.env', keys: serverKeys },
  { path: 'ai/.env', keys: aiKeys },
  { path: 'web/apps/client/.env', keys: publicKeys },
  { path: 'web/apps/admin/.env', keys: publicKeys },
  { path: 'desktop/.env', keys: publicKeys },
  { path: 'mobile/.env', keys: mobileKeys },
];

for (const t of targets) {
  const full = join(metaRoot, t.path);
  mkdirSync(dirname(full), { recursive: true });
  const content = renderEnv(vars, t.keys, envName);
  writeFileSync(full, content, 'utf8');
  console.log(`✅ ${t.path}`);
}

console.log(`\n🌍 Active environment: ${envName} (${vars.VISTA_ENV_LABEL ?? envName})`);
console.log('   Restart dev servers (web/desktop/mobile/server) to pick up changes.\n');

function parseEnv(text) {
  const out = {};
  for (const line of text.split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const i = t.indexOf('=');
    if (i < 1) continue;
    out[t.slice(0, i).trim()] = t.slice(i + 1).trim();
  }
  return out;
}

function renderEnv(vars, keys, envName) {
  const lines = [
    `# Generated by apply-env.mjs — do not edit by hand`,
    `# Profile: ${envName}`,
    '',
  ];
  for (const k of keys) {
    if (vars[k] !== undefined) lines.push(`${k}=${vars[k]}`);
  }
  lines.push('');
  return lines.join('\n');
}
